# "make" to run "-s" silent
# One line runs in one process

# .PHONY: helloworld
COMPILER=gcc
COMPILERFLAGS=-I.
DEPS=test.h

# outputfile: dependecies
#	command to create the outputfile
%.o: %.c $(DEPS)
	# -c gives file.o intermediate object
	# -o specifies file name
	$(COMPILER) -c -o $@ $< $(COMPILERFLAGS)
output: main.o test.o
	$(COMPILER) -o output main.o test.o $(COMPILERFLAGS)

rule:
	cd /tmp ; pwd
	# Command
	pwd
	# To not show the file name in terminal
	@pwd

# Evaluating at the moment (with :)
# Gives STR1=""
STR1:="$(STR2)"
STR2="Hello"
echo $(STR1)

# Evaluating when called
# Gives STR1="Hello"
STR1="$(STR2)"
STR2="Hello"
echo $(STR1)

